### PR TITLE
Version 5.31.119

### PR DESCRIPTION
**Pull request by JWhitleyWork**
Updates the repository with release 5.31.119 from Kvaser.
Please tag this commit with the tag 5.31.119 when merged.

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
Also - @icolwell-as - can you inquire about either making me a maintainer on this repository or just transferring ownership to me? I intend to create a `kvaser_sdk_vendor` package for ROS1 and ROS2 which can be used to make `kvaser_interface` available on the ROS build farm and I'd be happy to maintain this package and that one.

**Comment by icolwell-as** [comment]
@JWhitleyWork, thanks for offering to take over some work. Just so we understand completely, will the proposed `kvaser_sdk_vendor` replace this `kvaser_linuxcan` repo? Meaning `kvaser_interface` will depend on `kvaser_sdk_vendor` instead of `kvaser_linuxcan`?

**Comment by JWhitleyWork** [comment]
@icolwell-as That is somewhat correct. This repository would stay in-place as the source for the SDK source code. However, instead of `kvaser_interface` requiring the `libcanlib-dev` from the AS repo, it would rely on `kvaser_sdk_vendor`, which would be released to the ROS build farm. In this way, `kvaser_interface` could also be released to the build farm.

**Comment by JWhitleyWork** [comment]
Note: the actual sensor drivers would still need to be packaged up into a Debian file as ROS packages aren't really capable of installing kernel modules. `kvaser_sdk_vendor` would contain just the `canlib` and `linlib` APIs.

**Comment by icolwell-as** [comment]
> Note: the actual sensor drivers would still need to be packaged up into a Debian file as ROS packages aren't really capable of installing kernel modules.

By "actual sensor drivers" you mean the `kvaser-drivers-dkms` available via `ppa:astuff/kvaser-linux` right?

I'm also confused why you need to be a maintainer of this repo in order to create a new `kvaser_sdk_vendor` repo? Is the idea that `kvaser_sdk_vendor` would submodule this repo? so that both the kernal package (`kvaser-drivers-dkms`) and the SDK (`kvaser_sdk_vendor`) stay in sync with each other in terms of version?

**Comment by JWhitleyWork** [comment]
@icolwell-as That is correct.

**Comment by icolwell-as** [comment]
@JWhitleyWork ok awesome! thanks for explaining all that, just getting my head wrapped around all this stuff now :smile: 

I agree with what you propose, makes sense to me and would be nice to have kvaser_interface on the ROS buildfarm. Let's aim to set this up for Noetic and leave previous ROS releases as-is (unless there's some reason to change them, that I'm missing).

**Comment by JWhitleyWork** [comment]
Noetic only is fine with me on the ROS1 side. Really, I'm hoping to target Dashing and Foxy on the ROS2 side as well.

**Comment by JWhitleyWork** [comment]
And regarding maintainership, you're correct that I don't need to be a maintainer of this repo in order to create the other repo. I'll work on that seperately.

**Review by icolwell-as — APPROVED** [review]

**Review by dvangeyn-as — APPROVED** [review]

**Comment by JWhitleyWork** [comment]
Thanks, guys!

**Pull request merged**
