### PR TITLE
Version 5.33.212

### PR DESCRIPTION
**Pull request by JWhitleyWork**
New release - version 5.33.12 - required to work with kernel 5.6 and higher. Please tag HEAD of `master` with `5.33.212` after merge.

### CODE REVIEW

**Comment by icolwell-as** [comment]
Thanks @JWhitleyWork for opening this. What purpose will this version serve if it will be immediately superseded by 5.34.317?
Is the idea to try to follow the kvaser releases for documentation purposes? So it's easier to search/view diffs between versions, etc.

**Review by icolwell-as — APPROVED** [review]

**Review by dvangeyn-as — APPROVED** [review]

**Comment by JWhitleyWork** [comment]
@icolwell-as Yes, that is correct. This repo was intended to be an exact 1-to-1 copy of the released versions from upstream.

**Comment by JWhitleyWork** [comment]
FYI, this version is the minimum required to run this driver on Ubuntu 20.04 / kernel 5.4. Please let me know how soon this can be released.

**Comment by icolwell-as** [comment]
@JWhitleyWork, do you know if the newer kernel modules backwards compatible? So if we release new versions of kvaser-canlib and kvaser-dkms, will an older/existing version of the kvaser-interface ROS package still work with the new kvaser-canlib?

Just wondering how many things we'd need to release.

**Comment by JWhitleyWork** [comment]
Yes, it should be backward-compatible. At the very least, to the kernel used for 18.04.

**Comment by icolwell-as** [comment]
Ok sounds good, in that case, we should be able to do a release whenever is convenient. I'll say end of next week at the latest.

**Comment by icolwell-as** [comment]
@JWhitleyWork, the latest version (5.34.317) has been released on bionic and focal:
https://launchpad.net/~astuff/+archive/ubuntu/kvaser-linux/+packages

**Comment by JWhitleyWork** [comment]
@icolwell-as Thanks for the update! I'll let the IAC students know.

**Pull request merged**
